### PR TITLE
feat: Add hover scrolling interface for the form builder

### PR DESCRIPTION
**Pull request by GreatWizard**
Add a hover zone at top and bottom of the builder form to help user to scroll when drag'n'dropping things.

scroll

review: @xcambar @nlhkabu

### CODE REVIEW

**Comment by GreatWizard** [comment]
ping @nlh for design purpose :)

**Comment by nlhkabu** [comment]
:+1:

**Comment by GreatWizard** [comment]
https://github.com/jgwhite/ember-sortable/pull/104

**Comment by xcambar** [comment]
So, we should wait for the lib to import it, or... ?

**Comment by GreatWizard** [comment]
We will use this feature, because the lib concerns only the sort, no the drag n drop from the toolbar

**Comment by xcambar** [comment]
👍

**Pull request merged**
