### PR TITLE
Setup addon formidable-bs3

### PR DESCRIPTION
**Pull request by GreatWizard**
- [x] Split bs3 and core addons
- [x] Add a new partial for helpText in each fields
- [x] Move BS3Tooltip mixins into bs3 addon

- [x] Rename exposed component to have bs3 prefix and use it in the app

- [x] Update tests

### CODE REVIEW

**Comment by GreatWizard** [comment]
Next step: Rename exposed component to have bs3 prefix and use it in the app

**Comment by xcambar** [comment]
Nice! Can you add a `throws` test for the default implementation of `fmd-field` <=> "it throws if `getComponentName` is not overridden", please?

**Comment by GreatWizard** [comment]
Already here https://github.com/novafloss/formidable-ui/pull/149/files#diff-269148ea12eb20333eaa81a22d5d1105R22

**Comment by xcambar** [comment]
My bad. 
Awesome.

**Pull request merged**
